apiVersion: v1
kind: Service
metadata:
  name: projet-infra-3-frontend-service
spec:
  selector:
    app: projet-infra-3-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer