name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build Spring Boot App
      run: |
        cd projet_infra_3_backend
        ./mvnw clean install
      working-directory: ./projet_infra_3_backend

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build Angular App
      run: |
        cd projet_infra_3_frontend
        npm install
        ng build --prod
      working-directory: ./projet_infra_3_frontend

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to AKS (Dev)
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f mongodb-secret.yaml
